# Ativa o log para descobrirmos por que o lado direito não conecta
CONFIG_ZMK_USB_LOGGING=y

# Melhora a força do sinal Bluetooth entre as duas metades
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Nome que aparecerá no Bluetooth do computador
CONFIG_ZMK_KEYBOARD_NAME="Scylla MK2"